name: Makefile CI

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: |
        cd OpenWrt/openwrt-18.06.2/
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig # select your preferred configuration for the toolchain, target system & firmware packages.
        make # Build your firmware with make. This will download all sources, build the cross-compile toolchain and then cross-compile the Linux kernel & all chosen applications for your target system.

#    - name: configure
#      run: ./configure

#    - name: Install dependencies
#      run: make

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
